[features]
seeds = false
skip-lint = false
[programs.mainnet]
spl_staking = "9GAsSHWvHoHoqbk8tqHYCq3fcpyGmovgXD5GBkSo4p3f"
emperor_staking = "DVTouieqqLknDQn2UPE87HvWVizMkVj1Q4rqDgjNFYpK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
